### ISSUE TITLE
RPM on Centos 7.4 broken: Ec2 Permission denied

### ISSUE THREAD

**Issue by vmendoza** [widdix/aws-ec2-ssh#117] opened 2018-01-31 05:49 UTC
Operating System: Centos 7.4
AWS CLI Version: aws-cli/1.14.30 Python/2.7.5 Linux/3.10.0-693.11.6.el7.x86_64 botocore/1.8.34

SSHD AthorizedKeyCommand does not work, the response is always permission denied. 

The key has been uploaded to IAM and I've used ssh-add to add the key to the agent.

What I tried:
- running under "sudo -su nobody"  "/usr/bin/authorized_keys_command.sh user" works. The right key is returned from IAM
- Tried all the options fro here: https://gist.github.com/sivel/c68f601137ef9063efd7
- If I copy the pub key in ~/.ssh/authorized_keys works

**Comment by michaelwittig** [comment] 2018-01-31 06:57
Hi @vmendoza 

1. Which installation method have you used?
2. What error do you get? Please copy and paste the message

**Comment by vmendoza** [comment] 2018-01-31 15:42
I used the RPM method to install. 

- It looks like Centos / RHEL 7.4 works differently than other versions
- I have Cybereason for intrusion protection that might be blocking this but I doubt it.

**Comment by michaelwittig** [comment] 2018-01-31 21:26
The RPM only works on Amazon Linux at the moment. This is work in progress and will change soon.

**Comment by michaelwittig** [comment] 2018-02-05 18:17
duplicate of #115

**Closed by michaelwittig** 2018-02-05 18:17 UTC
Labels: bug

**Comment by michaelwittig** [comment] 2018-02-07 11:49
@vmendoza can you try the new RPM: https://s3-eu-west-1.amazonaws.com/widdix-aws-ec2-ssh-releases-eu-west-1/aws-ec2-ssh-1.7.0-1.el7.centos.noarch.rpm
