### ISSUE TITLE
install.sh fails to update /etc/ssh/sshd_config on Ubuntu 16.04

### ISSUE THREAD

**Issue by johnsweetescott** [widdix/aws-ec2-ssh#68] opened 2017-06-07 12:13 UTC
The install.sh script relies on finding a commented `#AuthorizedKeysCommand none` and `#AuthorizedKeysCommandUser nobody` in the `/etc/ssh/sshd_config` file. On Ubuntu 16.04 LTS (ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20170414 (ami-f1d7c395)) these commented entries are not present:
`$ grep -i AuthorizedKeysCommand /etc/ssh/sshd_config |  wc -l`
`0`
`$ grep -i AuthorizedKeysUser /etc/ssh/sshd_config | wc -l`
`0`
This means that the sed command:
`sed -i 's:#AuthorizedKeysCommand none:AuthorizedKeysCommand /opt/authorized_keys_command.sh:g' /etc/ssh/sshd_config`
does not change /etc/ssh/sshd_config.

Would it be possible to check for the existence of the string that the script is looking to substitute and append the string if it is not found?

**Comment by mariuz** [comment] 2017-06-26 10:50
Also in ubuntu 14.04 AuthorizedKeysCommand and AuthorizedKeysUser are missing from  /etc/ssh/sshd_config

**Comment by michaelwittig** [comment] 2017-08-02 09:38
I think the problem is that this solution is not intended to work with Ubuntu. The demo uses Amazon Linux https://github.com/widdix/aws-ec2-ssh#demo-with-cloudformation and also our tests (https://github.com/widdix/aws-ec2-ssh/tree/master/test) use Amazon Linux only.

Is anyone interested in fixing all the Ubuntu issues? I'm not using Ubuntu at all. I'm an Amazon Linux user.

**Comment by michaelwittig** [comment] 2017-08-22 14:12
fixed in #79

**Closed by michaelwittig** 2017-08-22 14:12 UTC
Labels: ubuntu
